import Head from 'next/head'
import Image from 'next/image'
import Feeds from '../components/Feeds'
import Sidebar from '../components/Sidebar'
import Widgets from '../components/Widgets'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex min-h-screen max-w-7xl mx-auto'>
        {/* Sidebar */}
        <Sidebar />

        {/* Feeds */}
        <Feeds />

        {/* Widgets */}
        <Widgets />

        {/* Modal */}
      </main>

    </div>
  )
}
