import Head from 'next/head'
import Image from 'next/image'
import Feeds from '../components/Feeds'
import Sidebar from '../components/Sidebar'
import Widgets from '../components/Widgets'

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex min-h-screen mx-auto'>
        {/* Sidebar */}
        <Sidebar />

        {/* Feeds */}
        <Feeds />

        {/* Widgets */}
        <Widgets newResults={props.newResults.articles} />

        {/* Modal */}
      </main>

    </div>
  )
}


// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
export async function getServerSideProps(){
  const newResults = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/business/us.json').then(
    (res) => res.json()
  )

  return {
    props : {
      newResults
    }
  }
}